### PR TITLE
issue/2925 change "disabled" to "visible" for "_styleAfterClick"

### PR DESCRIPTION
**Pull request by chucklorenz**
This PR changes the value "disabled" to "visible" to better reflect the behaviour and to reduce confusion. 

fixes https://github.com/adaptlearning/adapt_framework/issues/2925

### CODE REVIEW

**Review by moloko — APPROVED** [review]
makes sense!

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
@tomgreenfield authoring tools?

**Review by eleanor-heath — APPROVED** [review]

**Comment by oliverfoster** [comment]
superseded by #113

**Pull request closed without merging**
