### PR TITLE
Update adapt-contrib-trickle.js

### PR DESCRIPTION
**Pull request by develop-stuartohare**
Fixes a bug where trickle button does not appear when a component (e.g a text component) marks as complete on page load causing the completion queue to resolve incorrectly.

### CODE REVIEW

**Comment by hrajotia** [comment]
+1

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by LukaszGrela** [comment]
+1

**Comment by dancgray** [comment]
This will also need to go into develop branch so it's not behind master.

**Comment by dancgray** [comment]
+1

**Comment by dancgray** [comment]
@develop-stuartohare can you also create a PR for the develop branch

**Pull request merged**
