### PR TITLE
issue/49: debounce resize check

### PR DESCRIPTION
**Pull request by oliverfoster**
can overwhelm ie8

https://github.com/cgkineo/jquery.resize#1

need to move this library into adaptlearning

### CODE REVIEW

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-trickle/issues/49

**Comment by moloko** [comment]
+1

**Comment by tomgreenfield** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
