### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by oliverfoster**
* have really simplified to make it easier to understand (main point)
* have added startText inline with finishText
* have added "trickle:skip" event to skip a step lock
* have made all config runtime configurable (so you can change most of the properties on the fly)
* ~~is now notify aware but notify:opened event needs sorting out~~
* have tested in ie8, ie11, edge, iphone4 ios7, ipad ios9,  chrome, firefox
* handles subsequent lms sessions

### CODE REVIEW

**Comment by dancgray** [comment]
Nice. Very much easier to understand, lightly tested on Mac and iPad(iOS 8.1.1).

Will do some more testing early next week. 

It's a shame there is not a common method of dealing with resizing components, it does not play well combined with blockslider containing accordions and other expanding components.

**Comment by oliverfoster** [comment]
Yea, i've still yet to test against those properly :/ next week, i promise.

**Comment by brian-learningpool** [comment]
Very nice job. :+1:

**Comment by brian-learningpool** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by oliverfoster** [comment]
PLEASE DO NOT MERGE

**Comment by brian-learningpool** [comment]
@oliverfoster, is it ok to merge this?

**Comment by oliverfoster** [comment]
Nope, one more fix, two seconds - got a banked assessment glitch...

**Comment by oliverfoster** [comment]
Yup, good to merge

**Pull request merged**
